/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package campinggas;

import Controlador.UserControlador;
import Modelo.Actividad;
import Modelo.Cliente;
import Modelo.Parcelas;
import Patrones.Factory;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;

/**
 *
 * @author pablo
 */
public class ActividadesUser extends javax.swing.JFrame {

    /**
     * Creates new form ActividadesUser
     */
    int clientesTestCreados = 0;
    ArrayList<Actividad> actividades;
    public ActividadesUser(ArrayList<Actividad> actividades) {
        this.actividades = actividades;
        initComponents();
        actualizaElementos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaActividades = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        usuarioActividad = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaActividades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaActividades);

        jLabel1.setText("Actividades Disponibles");

        usuarioActividad.setText("Añadirme a la actividad");
        usuarioActividad.setActionCommand("AñadirUsuarioActividad");
        usuarioActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActividadActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usuarioActividad)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(botonVolver)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(usuarioActividad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActividadActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    public void setMiActionListener(ActionListener aL) {
        usuarioActividad.addActionListener(aL);
    }

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaActividades;
    private javax.swing.JButton usuarioActividad;
    // End of variables declaration//GEN-END:variables

    private void actualizaElementos() {
        Actividad a;
       DefaultListModel<String> model = new DefaultListModel<>();
       
       for(int i = 0; i < actividades.size(); i++)
       {/*
           a = actividades.get(i);
           a.getTitulo();*/
           
           model.addElement(actividades.get(i).getTitulo());
       }
       listaActividades.setModel(model);
    }

    
    public Cliente dameInfoCliente() {
       clientesTestCreados++;
       return Factory.crearCliente("Test"+String.valueOf(clientesTestCreados));
    } 
    
    public Actividad dameInfoActividad() {
        int i = 0;
        String selecionado = listaActividades.getSelectedValue();
        while(actividades.get(i).getTitulo() != selecionado)
            i++;
                
        return actividades.get(i);
    }

}